
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtrans-bot-config
  namespace: bots
  labels:
    app: rtrans_bot
data:
  DB_USER: rtrans_user
  DB_NAME: rtrans
  FLARESOLVER_URL: http://flaresolver.media.svc.cluster.local/v1
  RUST_LOG: info

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rtrans-bot
  namespace: bots
  labels:
    app: rtrans_bot
spec:
  serviceName: "rtrans-bot-service"
  replicas: 1
  selector:
    matchLabels:
      app: rtrans_bot
  template:
    metadata:
      labels:
        app: rtrans_bot
    spec:
      containers:
        - name: rtrans-bot
          image: redavtovo/r-trans-bot-rs:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rtrans-bot-config
            - secretRef:
                name: rtrans-bot-secrets
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtrans-bot-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: rtrans-bot-config
                  key: DB_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: rtrans-bot-config
                  key: DB_NAME
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
              claimName: rtrans
