name: PR builder

on:  
  label:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    
    - name: Get shortsha
      id: vars
      run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})
    
    - name: Build
      run: |
        docker build -t redavtovo/r-trans-bot-rs:${{ steps.vars.outputs.sha_short }} .

  push-deploy:
    if: github.event.label.name == 'deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Get shortsha
      id: vars
      run: |
         echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})

    - name: Deploy
      run: |
        docker tag redavtovo/r-trans-bot-rs:${{ steps.vars.outputs.sha_short }} redavtovo/r-trans-bot-rs:latest
        docker push redavtovo/r-trans-bot-rs:${{ steps.vars.outputs.sha_short }}
        docker push redavtovo/r-trans-bot-rs:latest

    - name: Prepare K8S
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy to K8S
      uses: Azure/k8s-deploy@v1
      with:
        namespace: bots
        manifests: deployment/manifest.yaml
        images: |
            redavtovo/r-trans-bot-rs:${{ steps.vars.outputs.sha_short }}
    